

services:
  nginx:
    container_name: nginx
    build: ./nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports: 
      - "8080:8080"
      - "8081:80" 
    restart: always
    volumes:
      - ./:/yii-application
    networks:
      - app-network
    env_file:
      - .env  
  php:
    container_name: php
    build: ./php
    volumes:
      - ./:/yii-application
    working_dir: /yii-application
    restart: always
    networks:
      - app-network
    env_file:
      - .env  

volumes:
  vietnamlab_db:
networks:
  app-network:
    ipam:
      config:
        - subnet: 172.18.0.0/16