

services:
  nginx:
    container_name: nginx
    build: ./nginx
    command: nginx -g "daemon off;"
    depends_on:
      - php
    ports: 
      - "8080:8080"
      - "8081:80" 
    restart: always
    volumes:
      - ./:/yii-application
    networks:
      - app-network
  php:
    container_name: php
    build: ./php
    volumes:
      - ./:/yii-application
    working_dir: /yii-application
    restart: always
    depends_on:
      - database
    networks:
      - app-network
  database:
    container_name: postgres
    image: postgres:17.0-alpine3.20
    restart: always
    ports:
      - 5435:5435
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - vietnamlab_db:/var/lib/postgresql/data
      - ./data:/data
    networks:
      - app-network
volumes:
  vietnamlab_db:
networks:
  app-network:
    driver: bridge